#!/usr/bin/env bash
# Anthill — one-line installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/fengty/anthill-agent/main/scripts/install.sh | bash
#
# What this script does:
#   1. Detects OS and required Python (>=3.9)
#   2. Clones anthill-agent to ~/.anthill-agent/
#   3. Sets up an isolated virtualenv
#   4. Installs anthill into the venv
#   5. Drops a wrapper at ~/.local/bin/anthill so `anthill` Just Works
#   6. Prints next-step setup instructions
#
# Designed to be idempotent — re-running upgrades to the latest main.

set -euo pipefail

ANTHILL_DIR="${ANTHILL_INSTALL_DIR:-$HOME/.anthill-agent}"
ANTHILL_REPO="${ANTHILL_REPO:-https://github.com/fengty/anthill-agent.git}"
ANTHILL_BRANCH="${ANTHILL_BRANCH:-main}"
BIN_DIR="${ANTHILL_BIN_DIR:-$HOME/.local/bin}"

# --- pretty output ---
BOLD=$'\033[1m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
RED=$'\033[31m'
DIM=$'\033[2m'
RESET=$'\033[0m'

say()  { printf "%s\n" "$*"; }
ok()   { printf "${GREEN}✓${RESET} %s\n" "$*"; }
info() { printf "${DIM}→${RESET} %s\n" "$*"; }
warn() { printf "${YELLOW}!${RESET} %s\n" "$*"; }
die()  { printf "${RED}✗${RESET} %s\n" "$*" >&2; exit 1; }

# --- preflight ---
say "${BOLD}Anthill installer${RESET}"
say ""

# Python
for py in python3.13 python3.12 python3.11 python3.10 python3.9 python3; do
  if command -v "$py" >/dev/null 2>&1; then
    PYTHON="$py"
    break
  fi
done
[ -z "${PYTHON:-}" ] && die "Python 3.9+ required. Install Python first, then re-run."

PYTHON_VERSION=$("$PYTHON" -c 'import sys; print("%d.%d" % sys.version_info[:2])')
PYTHON_OK=$("$PYTHON" -c 'import sys; print("yes" if sys.version_info >= (3, 9) else "no")')
[ "$PYTHON_OK" = "yes" ] || die "Found Python $PYTHON_VERSION, need >=3.9."
ok "Python $PYTHON_VERSION at $(command -v "$PYTHON")"

# Git
command -v git >/dev/null 2>&1 || die "git required."
ok "git at $(command -v git)"

# --- clone or update ---
if [ -d "$ANTHILL_DIR/.git" ]; then
  info "Existing install at $ANTHILL_DIR — updating"
  git -C "$ANTHILL_DIR" fetch --quiet origin "$ANTHILL_BRANCH"
  git -C "$ANTHILL_DIR" reset --hard "origin/$ANTHILL_BRANCH" --quiet
else
  info "Cloning into $ANTHILL_DIR"
  rm -rf "$ANTHILL_DIR"
  git clone --quiet --branch "$ANTHILL_BRANCH" "$ANTHILL_REPO" "$ANTHILL_DIR"
fi
ok "Source ready at $ANTHILL_DIR"

# --- venv ---
VENV="$ANTHILL_DIR/.venv"
if [ ! -d "$VENV" ]; then
  info "Creating virtualenv"
  "$PYTHON" -m venv "$VENV"
fi
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -e "$ANTHILL_DIR"
ok "Anthill installed into $VENV"

# --- wrapper ---
mkdir -p "$BIN_DIR"
WRAPPER="$BIN_DIR/anthill"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by anthill installer
exec "$VENV/bin/anthill" "\$@"
EOF
chmod +x "$WRAPPER"
ok "Wrapper at $WRAPPER"

# --- PATH check ---
case ":$PATH:" in
  *":$BIN_DIR:"*) PATH_OK=1 ;;
  *) PATH_OK=0 ;;
esac

say ""
ok "${BOLD}Anthill installed.${RESET}"

if [ "$PATH_OK" != "1" ]; then
  warn "$BIN_DIR is not on your PATH."
  warn "Add this to your shell profile (~/.zshrc or ~/.bashrc):"
  printf "${DIM}    export PATH=\"\$HOME/.local/bin:\$PATH\"${RESET}\n"
fi

say ""
say "${BOLD}Next steps:${RESET}"
say "  1. Set at least one model key (DeepSeek is the cheapest sane default):"
say "       export ANTHILL_DEEPSEEK_KEY=\"sk-...\""
say "  2. Found your first nation:"
say "       anthill init"
say "       anthill spawn --count 4"
say "  3. Give it work:"
say "       anthill ask \"用一句话解释什么是信息素路由\""
say ""
say "${DIM}Re-run this installer any time to upgrade to the latest main.${RESET}"
